wersja_ostateczna_forum/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wersja_ostateczna_forum.Models
{
    public class Category
    {
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public virtual ICollection<Moderator> Moderators { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public int SectionID { get; set; }
        public virtual Section Section { get; set; }
        public string Description { get; set; }

    }
}

wersja_ostateczna_forum/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wersja_ostateczna_forum.Models;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;

namespace wersja_ostateczna_forum.Controllers
{
    public class CategoriesController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories/forum/5
        public ActionResult forum(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Item item = db.Items
            // .Include(i => i.Category)
            // .Include(i => i.Brand)
            // .SingleOrDefault(x => x.ItemId == id);


            //var threads = db.Threads.Include(t => t.Category).Include(t => t.Posts).ToList().s(x => x.CategoryID == id);
            var lista_watkow = db.Categories.Find(id).Threads.ToList().OrderByDescending(x => x.DateTime);
            ViewBag.kategoria = db.Categories.Find(id).Title;
            if (lista_watkow == null)
            {
                return HttpNotFound();
            }
            return View(lista_watkow.ToPagedList(page ?? 1, 10));
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.SectionID = new SelectList(db.Sections, "SectionID", "Title");
            return View();
        }
        public ActionResult create_topic(int CategoryID)
        {
            ViewBag.dzialaj = CategoryID;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult create_topic(Category_Topic_Post zbieranina)//otrzymuje tytul i content
        {
            ///najpierw stworzyc nowy watek
            var topic = new Thread();
            topic.CategoryID = zbieranina.CategoryID;
            topic.Owner = User.Identity.GetUserName();
            topic.Title = zbieranina.Title;
            topic.DateTime = DateTime.Now;
            db.Threads.Add(topic);
            db.SaveChanges();
            // sie udalo
            //teraz utworzyc post do watku
            var post = new Post();
            post.Content = zbieranina.Content;
            post.DateTime = topic.DateTime;
            post.UserID = User.Identity.GetUserId();
            post.ThreadID = topic.ThreadID;
            db.Posts.Add(post);
            db.SaveChanges();
            //powinno sie utworzyc




            //post.DateTime = DateTime.Now;
            //post.UserID = User.Identity.GetUserId();
            //if (ModelState.IsValid)
            //{
              //  db.Posts.Add(post);
               // db.SaveChanges();
              //  return RedirectToAction("topic/1");
            //}
            return View();
        }
        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Title,SectionID")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SectionID = new SelectList(db.Sections, "SectionID", "Title", category.SectionID);
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.SectionID = new SelectList(db.Sections, "SectionID", "Title", category.SectionID);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,Title,SectionID")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SectionID = new SelectList(db.Sections, "SectionID", "Title", category.SectionID);
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public class Formatter : IFormatProvider, ICustomFormatter
        {
            public object GetFormat(Type formatType)
            {
                if (formatType == typeof(ICustomFormatter))
                    return this;

                return null;
            }

            public string Format(string format, object arg, IFormatProvider formatProvider)
            {
                if (!(arg is DateTime)) throw new NotSupportedException();

                var dt = (DateTime)arg;

                string suffix;

                if (new[] { 11, 12, 13 }.Contains(dt.Day))
                {
                    suffix = "th";
                }
                else if (dt.Day % 10 == 1)
                {
                    suffix = "st";
                }
                else if (dt.Day % 10 == 2)
                {
                    suffix = "nd";
                }
                else if (dt.Day % 10 == 3)
                {
                    suffix = "rd";
                }
                else
                {
                    suffix = "th";
                }

                return string.Format("{0:MMMM} {1}{2}, {0:yyyy}", arg, dt.Day, suffix);
            }
        }
    }
}

wersja_ostateczna_forum/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wersja_ostateczna_forum.Models;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;

namespace wersja_ostateczna_forum.Controllers
{
    public class ThreadsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public static Thread GetThreadByID(int id)
        {
            var db = new ApplicationDbContext();
            return db.Threads.Find(id);
        }
        // GET: Threads
        public ActionResult Index()
        {
            var threads = db.Threads.Include(t => t.Category);
            return View(threads.ToList());
        }

        // GET: Threads/Details/5
        public ActionResult topic(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var thread = db.Threads.Find(id).Posts.ToList();
            ViewBag.watek = db.Threads.Find(id).Title;
            ViewBag.liczba_postow = db.Threads.Find(id).Posts.Count.ToString();
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread.ToPagedList(page ?? 1, 10));
        }

        // GET: Threads/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Title");
            return View();
        }

        /// <summary>
        /// ////////post
        /// </summary>
        /// <param name="post"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Do(Post post)
        {
            post.DateTime = DateTime.Now;
            post.UserID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("topic/1");
            }
            return View();
        }

        // POST: Threads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ThreadID,Title,DateTime,CategoryID,Owner")] Thread thread)
        {
            if (ModelState.IsValid)
            {
                db.Threads.Add(thread);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Title", thread.CategoryID);
            return View(thread);
        }

        // GET: Threads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Title", thread.CategoryID);
            return View(thread);
        }

        // POST: Threads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ThreadID,Title,DateTime,CategoryID,Owner")] Thread thread)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thread).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Title", thread.CategoryID);
            return View(thread);
        }

        // GET: Threads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thread thread = db.Threads.Find(id);
            if (thread == null)
            {
                return HttpNotFound();
            }
            return View(thread);
        }

        // POST: Threads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Thread thread = db.Threads.Find(id);
            db.Threads.Remove(thread);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

wersja_ostateczna_forum/Views/Categories/Create.cshtml
@model wersja_ostateczna_forum.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionID, "SectionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SectionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wersja_ostateczna_forum/Views/Categories/Delete.cshtml
@model wersja_ostateczna_forum.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Section.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Section.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

wersja_ostateczna_forum/Views/Categories/Edit.cshtml
@model wersja_ostateczna_forum.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionID, "SectionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SectionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SectionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wersja_ostateczna_forum/Views/Categories/Index.cshtml
@model IEnumerable<wersja_ostateczna_forum.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Section.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Section.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CategoryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CategoryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CategoryID })
        </td>
    </tr>
}

</table>

wersja_ostateczna_forum/Views/Categories/create_topic.cshtml
@using Microsoft.AspNet.Identity
@model wersja_ostateczna_forum.Models.Category_Topic_Post

@{
    ViewBag.Title = "create_topic";
}
<h2>create_topic</h2>
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("create_topic", "Categories", FormMethod.Post))
    { 
@Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thread</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.Hidden("CategoryID", (object)ViewBag.dzialaj);


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

wersja_ostateczna_forum/Views/Categories/forum.cshtml
@using PagedList;
@using PagedList.Mvc;
@using wersja_ostateczna_forum.Controllers
@model  IPagedList<wersja_ostateczna_forum.Models.Thread>

@{
    ViewBag.Title = "Details";

}
<style>
    #kategoria:hover {
        background-color: #889daf;
        color: white;
    }

    a {
        color: #0a0226;
    }

        a:hover {
            color:#11737d;
            text-decoration: none;
        }
</style>
<div class="container" style="border: 1px solid #e3e3e3;
  border-radius: 4px;">
    <div class="row" style="height: 70px;background-color:#889daf; padding-left:5px; padding-top:10px; padding-right:10px;">
    <div class="col-md-12"><h4>@ViewBag.kategoria</h4></div>

    </div>
    <div class="row" style="height: 50px;background-color:#556a7f;padding-top:5px;">
        @if (Request.IsAuthenticated)
        {
            <div class="col-md-offset-10">
                <div class="col-md-3"></div>
        <div class="btn btn-default col-md-9" style="text-align:center; height:35px; width:120px;"><h4>@Html.ActionLink("New thread", "create_topic", new { CategoryID = Model.FirstOrDefault().CategoryID })</h4></div>
            </div>

        }
    </div>
@foreach (var item in Model)
{


    <div class="row" style="border: 1px solid #e3e3e3;
  border-radius: 4px">
            <div style="height: 70px; padding-top:5px; padding-left:5px;" class="col-md-8">
                <a href="@Url.Action("topic", "Threads", new { id = item.ThreadID }, null)">

                    <div class="tiletext"><h4>@item.Title</h4></div>
                </a>
                        <div class="tilesubtext">By @item.Owner, @string.Format("{0:dd}{1} {0:MMMM yyyy}", item.DateTime, "")</div>
                       
                    
                
            </div>
        <div style="height: 70px;" class="col-md-1">
            <div class="row" style="padding-top:5px; text-align:center;">@item.Posts.Count()</div>
            <div class="row" style="text-align:center">Replies</div>
            
        </div>
        <div style="height: 70px;" class="col-md-3">
            <div class="col-md-4" style="padding-top:5px">

                <img src="@Url.Content(@item.Posts.LastOrDefault().User.Avatar)" width="65" height="65" style="border-radius: 50%; padding-bottom:5px;text-align: center;
vertical-align: middle;" />

            </div>
            <div class="col-md-8" style="text-align:center; padding-top:5px;">

       

                <div class="row" style="padding-bottom:5px;">@item.Posts.LastOrDefault().User.Nick</div>
                <div class="row">@string.Format("{0:dd}{1} {0:MMMM yyyy}", item.Posts.LastOrDefault().DateTime, "")</div>
                
            </div>
        </div>
    </div>


                    }
    <div style="height: 50px;background-color:#556a7f" class="row"></div>
</div>
<div style="text-align:right">
    @Html.PagedListPager(Model, page => Url.Action("forum", new { page }))
</div>